name: "Finish Release or Hotfix"

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  merge-master-into-develop:
    name: "Merge master back into develop"
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true # Only merged pull requests must trigger this job
    steps:
      - uses: actions/checkout@v2

      - name: Extract version from branch name (for release branches)
        if: startsWith(github.event.pull_request.head.ref, 'release/')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release/}
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "BRANCH_TYPE=\"release\"" >> $GITHUB_ENV

      - name: Extract version from branch name (for hotfix branches)
        if: startsWith(github.event.pull_request.head.ref, 'hotfix/')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#hotfix/}
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "BRANCH_TYPE=\"hotfix\"" >> $GITHUB_ENV

      - name: Create Release
        uses: thomaseizinger/create-release@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: ${{ github.event.pull_request.merge_commit_sha }}
          tag_name: ${{ env.RELEASE_VERSION }}
          name: ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: master
          destination_branch: develop
          pr_title: Merge Master Back Into Develop
          pr_label: ${{ env.BRANCH_TYPE }}
          pr_reviewer: ${{ github.event.pull_request.merged_by.login }} # By default, we request a review from the person who triggered the workflow.
          pr_assignee: ${{ github.event.pull_request.merged_by.login }}
          pr_body: |
            This PR merges the master branch for ${{ env.BRANCH_TYPE }} ${{ env.RELEASE_VERSION }} back into develop.
            This happens to ensure that the updates that happend on the ${{ env.BRANCH_TYPE }} branch, i.e. version number updates are also present on develop.
            **Note**: You shouldn't squash and merge this PR. Use a normal merge instead.
