name: Start a new hotfix

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: Version Number
        required: false
jobs:
  start-new-hotfix:
    name: Start a new hotfix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Set var
        run: |
          version_number=5555
          
      - name: Create hotfix branch
        run: git checkout -b ${{ github.event.inputs.version_number }}

      - name: Initialize mandatory git config
        run: |
          git config user.name "Omar Labib"
          git config user.email omar.labib@swvl.com

      - name: Print stuff
        run: |
            echo "hhhh"
          echo ${version_number}

      - name: Bump version
        run: |
          sed -i'' 's/MARKETING_VERSION \= [^\;]*\;/MARKETING_VERSION = ${{ github.event.inputs.version_number }};/' GithubWorkFlows.xcodeproj/project.pbxproj
          perl -i -pe 's/(CURRENT_PROJECT_VERSION = )(\d+)(\;)$/$1.($2+1).$3/e' GithubWorkFlows.xcodeproj/project.pbxproj

      - name: Commit changes
        id: make-version-commit
        run: |
          git add .
          git commit --message "Bump version number"
          echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Push hotfix branch
        run: git push origin ${{ github.event.inputs.version_number }}
